language: python

python:
  - "2.7"
fail_fast: true

before_install:
  - which python; python --version
  - pip install -r requirements.txt
  # Stop the build if it doesn't pass syntax and complexity checks
  - flake8 . --count --show-source --max-complexity=8 --statistics

install:
  - pip install -r requirements.txt
#  - pip install .

